version: 0.2

env:
  secrets-manager:
    #    Old Values
    #    BUCKET_NAME: wrkshpSecrets:bucketname
    #    backendPrivateIP: wrkshpSecrets:backendPrivateIP
    #    New Values
    BUCKET_NAME: wrkshpSecrets:Reports
    backendPrivateIP: wrkshpSecrets:AppServer_PrivateIP
    region: wrkshpSecrets:Region
    publicIP: wrkshpSecrets:AppServer_PublicIP
    albURL: wrkshpSecrets:ApplicationURL_DevEnv
    #variables:
    # key: "value"
    # key: "value"
    #parameter-store:
    # key: "value"
    # key: "value"
    #secrets-manager:
    # key: secret-id:json-key:version-stage:version-id
    # key: secret-id:json-key:version-stage:version-id
    #exported-variables:
    # - variable
    # - variable
  #git-credential-helper: yes

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      # - cd /tmp/
      - curl -s --connect-timeout 8 -d "{\"privateIP\":\"$backendPrivateIP\",\"publicIP\":\"$publicIP\",\"region\":\"$region\",\"bucket\":\"$BUCKET_NAME\"}"   -H 'Content-Type:application/json' http://$backendPrivateIP:3337/api/v1/aws_dashboard_report/secrets/update || true
      - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/bin/chromedriver
      - chromedriver --version
      - curl https://intoli.com/install-google-chrome.sh | bash
      - mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
      - google-chrome --version && which google-chrome
      #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
      #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
      #runtime-versions:
      # name: version
      # name: version
#    commands:
    # - command
    #pre_build:
    #commands:
    # - command
    # - command
  build:
    commands:
      - mvn clean test -Dcucumber.options="--tags @Smoke" -DExecutionPlatform="AWS_CHROME"
      # - command
      # - command
  post_build:
    commands:
      - aws s3 cp . s3://$BUCKET_NAME/awswrkshp_functional_assurance_smoke/ --recursive --exclude "*" --include "*.html"
      # - command
      # - command
      #reports:
      #report-name-or-arn:
      #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
    #artifacts:
    #files:
    #- "target/*"
    # - location
    # - location
    #name: $(date +%Y-%m-%d)
    #discard-paths: yes
    #base-directory: location
    #cache:
    #paths:
    # - paths